name: cd-homolog

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:

  render-homolog:
    runs-on: ubuntu-latest
    needs: docker-hub

    steps:
      - name: Novo deploy Homologacao
        run: curl --fail --silent --show-error --request POST "${{ secrets.RENDER_HOMOLOG_DEPLOY_HOOK_URL }}"