name: build

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout no repositorio
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-project

      - name: Build da aplicação
        run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout no repositorio
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-project

      - name: Testes da aplicação
        run: npm run test

  test-integracao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout no repositorio
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-project

      - name: Subir banco de dados
        run: docker compose up -d db

      - name: Aguardar banco de dados
        run: until docker compose exec -T db pg_isready -U app-js; do sleep 1; done

      - name: Teste de integração
        run: npm run test:integration
        env:
          DB_HOST: 127.0.0.1

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout no repositorio
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-project

      - name: Teste do Lint
        run: npm run lint

  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout no repositorio
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Rodando SonarQube
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.organization=gabrielduarterb
            -Dsonar.projectKey=GabrielDuarteRB_api-js
            -Dsonar.qualitygate.wait=true

  sast:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout no repositorio
        uses: actions/checkout@v6

      - name: Inicializando o CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript-typescript

      - name: Analisar
        uses: github/codeql-action/analyze@v4

